name: Build Dashboard

on:
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: [self-hosted, Linux]
    if: (github.event.label.name == 'Bug ğŸ') || (github.event.label.name == 'Bug ğŸ')

    steps:
    - uses: actions/checkout@v2
    - uses: timheuer/issue-notifier@v1
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      with:
        fromMailAddress: 'no-reply@mistica.com'
        toMailAddress: 'yceballost@gmail.com'
        subject: 'A new component request!'
        labelsToMonitor: 'Bug ğŸ'